# -*- coding: utf-8 -*-
"""mod1_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f85ltOjstmK789UgpIQ1f2P8gJ4OHakc
"""

import cv2
import numpy as np
import os

video_path = 'video.mp4'

output_folder = 'normalized_frames'
os.makedirs(output_folder, exist_ok=True)

cap = cv2.VideoCapture(video_path)
frame_count = 0

ret, frame = cap.read()
print(ret)
print(frame)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break  # Exit if no frames left to read

    # Convert frame to float32 for normalization
    frame = frame.astype(np.float32)
    denoised_frame = cv2.GaussianBlur(frame, (5, 5), 0)

    # Apply min-max scaling to normalize between [0, 1]
    min_val = np.min(denoised_frame)
    max_val = np.max(denoised_frame)
    normalized_frame = (denoised_frame - min_val) / (max_val - min_val)

    # Save the normalized frame as a .npy file
    output_path = os.path.join(output_folder, f'frame_{frame_count:04d}.npy')
    np.save(output_path, normalized_frame)

    frame_count += 1

cap.release()
print(frame_count)
print(f"Saved {frame_count} denoised and normalized frames in '{output_folder}'.")

# Download the deploy.prototxt and mobilenet_iter_73000.caffemodel files
# !wget https://github.com/chuanqi305/MobileNet-SSD/blob/master/deploy.prototxt -O deploy.prototxt
# !wget https://github.com/chuanqi305/MobileNet-SSD/blob/master/mobilenet_iter_73000.caffemodel -O mobilenet_iter_73000.caffemodel

# Load the pre-trained model
net = cv2.dnn.readNetFromCaffe('/content/deploy.prototxt', '/content/mobilenet_iter_73000.caffemodel')

# Now you can proceed with detecting people in the frames

# Verify if the files are in the correct directory
# !ls /content/